[FIX] delivery_ups: test same tracking ref
UPS test mode API does not provide unique tracking references anymore,
this test is therefore wrong.

```
Traceback (most recent call last):
  File "/home/odoo/src/enterprise/delivery_ups/tests/test_delivery_ups.py", line 261, in test_04_backorder_and_track_number
    self.assertNotEqual(out01.carrier_tracking_ref, out02.carrier_tracking_ref)
AssertionError: '1ZXXXXXXXXXXXXXXXX' == '1ZXXXXXXXXXXXXXXXX'
```

X-original-commit: 6c11abc7beb1a2e4983f6f5b14aefede95517f05
Part-of: odoo/enterprise#34186