[FIX] sale_subscription: Correct invoice creation when no start_date
Steps:
    - install `sale_subscription` with demo-data
    - Go to subscription
    - Create a new one
    - Set Monthly subscription with `Office Cleaning Service (SUB)`
    - Set quantity to 2.0
    - Confirm
    - Create Invoice (Regular Invoice)
    - Go back to subscription
    - Click to Upsell
    - Remove `start_date`
    - Set quantity to 4.0
    - Save
    - Confirm
    - Create Invoice
    - Traceback
```
...
 File "/home/odoo/src/enterprise/saas-16.3/sale_subscription/models/sale_order_line.py", line 259, in _prepare_invoice_line

    new_period_start = max(self.order_id.start_date or fields.Datetime.today(), self.order_id.first_contract_date)

TypeError: can't compare datetime.datetime to datetime.date
```

Because `self.order_id.start_date` is `False` we fallback
to `fields.Datetime.today()`, but if we compare it to
`self.order_id.first_contract_date`, a traceback will be raised.

A solution could be to use `Date` instead of `Datetime` to match
`first_contract_date` field type

closes odoo/enterprise#47880

X-original-commit: 4c3219d18883136ab30fe927b7a49b17b73bd210
Signed-off-by: Arnaud Joset (arj) <arj@odoo.com>
Signed-off-by: Achraf Ben Azzouz (abz) <abz@odoo.com>