[FIX] account_reports: Balance sheet error with account groups
Have Account groups defined for the current company
Open Balance Sheet
Enable "Hierarchy and Subtotals" option
Click on unfoldable line twice

Issue. error message pops up.
OwlError: Got duplicate key in t-foreach: ~account.group~

This occurs because the new lines fetched for the group info have no reference
to the parent line. As result the fold/unfold mechanism is not working
properly and fetching more lines will raise duplication issues

opw-3521189

closes odoo/enterprise#48820

X-original-commit: 40eaf5f352441152cb5d66dabc169b1463b72dfc
Signed-off-by: Olivier Colson (oco) <oco@odoo.com>
Signed-off-by: Andrea Grazioso (agr) <agr@odoo.com>