[FIX] quality_control_worksheet: error on validation
When saving the worksheet in quality_mrp_workorder_worksheet, no action is returned on a pass so we get a:
TypeError: Cannot read properties of undefined (reading 'context')

This fix ensures that nothing needs to be done if no action is returned and we can also remove the useService("action").

closes odoo/enterprise#37963

X-original-commit: 8189ae41afbf5a9fadab6e1531bc39f2e91f56df
Signed-off-by: Arnold Moyaux (arm) <arm@odoo.com>
Signed-off-by: Diez Stéphane (snd) <snd@odoo.com>