[FIX] hr_contract_salary: work without a bank account
When the bank account is not shown because the salary structure
doesn't apply the following traceback occurred:

Traceback (most recent call last):
  ...
  File ".../addons/hr_contract_salary/controllers/main.py", line 578, in update_salary
    new_contract = self.create_new_contract(contract, advantages)
  File ".../addons/l10n_be_hr_contract_salary/controllers/main.py", line 306, in create_new_contract
    new_contract = super().create_new_contract(contract, advantages, no_write=no_write, **kw)
  File ".../addons/hr_contract_salary/controllers/main.py", line 552, in create_new_contract
    self._update_personal_info(employee, contract, personal_infos, no_name_write=bool(kw.get('employee')))
  File ".../addons/hr_contract_salary/controllers/main.py", line 514, in _update_personal_info
    ('acc_number', '=', bank_account_vals['acc_number'])], limit=1)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File ".../http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'acc_number'

This solves this issue by not trying to create or find a bank account
if no bank account information was provided.

opw-2747520

closes odoo/enterprise#23849

X-original-commit: 38641298ec5c910e631f4a829b8cad8c53420455
Signed-off-by: Yannick Tivisse (yti) <yti@odoo.com>