[FIX] website_calendar: validate required checkboxes
On the website, if an online appointment form contains a required
checkbox, the user can book an appointment even if he didn't check any
box.

To reproduce the error:
(Use demo data)

1. In Online Appointments, edit "Schedule a Demo"
2. Add a question Q:
    - Question Type: Checkboxes
        - Required Answer: True
    - Go to Website
    - Book a slot with selecting any checkbox

Error: The appointment is booked. However, Q is required and no boxes
have been checked.

OPW-2473001

closes odoo/enterprise#18004
closes odoo/odoo#70005

closes odoo/enterprise#18124

X-original-commit: 3de1a112fcae378da2c97d24f34c59efedea01e4
Signed-off-by: Nicolas Lempereur (nle) <nle@odoo.com>
Signed-off-by: Adrien Widart <adwid@users.noreply.github.com>