[FIX] delivery_dhl,delivery_fedex,delivery_ups: fix test shipping_weight not set
Since the commit: https://github.com/odoo/odoo/commit/42714e2202e20366dddf2ae524937d6298de1f78
the `shipping_weight` may not be computed in the wizard.

```
Traceback (most recent call last):
  File "/home/odoo/src/enterprise/delivery_fedex/tests/test_delivery_fedex.py", line 291, in test_03_fedex_multipackage_international_flow
    super().test_03_fedex_multipackage_international_flow()
  File "/home/odoo/src/enterprise/delivery_fedex/tests/test_delivery_fedex.py", line 207, in test_03_fedex_multipackage_international_flow
    self.assertGreater(picking.shipping_weight, 0.0, "Picking weight should be positive.")
AssertionError: 0.0 not greater than 0.0 : Picking weight should be positive.
```

This commit ensures that the `shipping_weight` is computed.

X-original-commit: 53104d66ade9f30e8aaad1862dd129f3282f1329
Part-of: odoo/enterprise#34186