Cherry pick of c98c6e929528378d1e978d5e03e93ef918fd9e9b failed
stdout:

stderr:

closes odoo/enterprise#9255

Error: could not apply c98c6e9295... [FIX] hr_expense_predict_product: minor fixes
Hint: after resolving the conflicts, mark the corrected paths
Hint: with 'git add <paths>' or 'git rm <paths>'
Hint: and commit the result with 'git commit'
Signed-off-by: Florian Daloze (fda) <fda@odoo.com>