[FIX] l10n_cl_edi: correct translations
A small oversight in https://github.com/odoo/enterprise/pull/37891
introduced faulty translations with a different amount of "%s" items
compared to the strings in the source code. This leads to TypeErrors:

  File "...l10n_cl_edi/models/account_move.py", line 480, in _l10n_cl_action_response
    msg = _('Document %s failed with the following response:') % (action_response[status_type].description) + \
TypeError: not all arguments converted during string formatting

This commit fixes those faulty translations. Strings prepended with #|
were not updated because those refer to "Previously untranslated"
strings [1].

To fix the problem in affected databases the l10n_cl_edi module needs
to be updated or the Spanish translations must be updated via the
technical settings.

Spanish translations provided by VBE.

opw-3415429

[1] https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

closes odoo/enterprise#44091

Signed-off-by: Josse Colpaert <jco@odoo.com>
Co-authored-by: Valentino Bedetta <vbe@odoo.com>