[FIX] account_invoice_extract: edit moves without account features
This follows revision
odoo/odoo@5ccc32fcf72cbfb6bb077d99a7657416c502aac1

Before the above revision,
the invoice OCR extraction was working
even for a user which did not have the
accounting features group
(at least Show Accounting Features - Readonly)

The code is editing the invoice move lines even
if they are invisible, which is not possible
in a real form view.
However, as here the goal is not to test the form view
behavior, we can bypass this invisible mecanism
so the code works as before,
able to edit the move lines even if they are invisible
to the user executing the code.

```
odoo.addons.account_invoice_extract.tests.test_invoice_extract:285

FAIL: TestInvoiceExtract.test_multi_currency
Traceback (most recent call last):
  File "/data/build/enterprise/account_invoice_extract/tests/test_invoice_extract.py", line 285, in test_multi_currency
    invoice.with_user(test_user)._check_status()
  File "/data/build/enterprise/account_invoice_extract/models/account_invoice.py", line 737, in _check_status
    self._save_form(ocr_results)
  File "/data/build/enterprise/account_invoice_extract/models/account_invoice.py", line 869, in _save_form
    with move_form.line_ids.edit(i) as line:
  File "/data/build/odoo/odoo/tests/common.py", line 2619, in edit
    self._assert_editable()
  File "/data/build/odoo/odoo/tests/common.py", line 2540, in _assert_editable
    assert not self._parent._get_modifier(self._field, 'invisible'),\
AssertionError: field line_ids is not visible
```

closes odoo/enterprise#29316

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>