[FIX] sale_subscription: don't crash on public user renewals
To reproduce:

1/ Set Monthly Subscription subscription template to
   "Create Invoice": "Send after successful payment"
2/ Enable the test payment acquirer
3/ Set "To renew" on the existing Monthly subscription
4/ Open the portal view without being logged in
5/ Pay

This results in the traceback at the end of this commit message.

It's caused by odoo/odoo@8ae1a43663687 which stopped sudo() from
propagating to the records that the report renders. To solve it switch
to the superuser as far down the call stack as possible. To be safe
make sure a caller has sudo'd before switching. Normally this is done
by the payment.acquirers when calling _handle_feedback_data().

Similar to odoo/odoo@e6800845cd8, odoo/odoo@962919ec878b and others.

Traceback:
odoo.addons.base.models.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: account.move
...
File "/home/jvo/odoo_versions/odoo_v15/odoo/http.py", line 536, in response_wrap
  response = f(*args, **kw)
File "/home/jvo/odoo_versions/odoo_v15/addons/payment_stripe/controllers/main.py", line 45, in stripe_return_from_checkout
  request.env['payment.transaction'].sudo()._handle_feedback_data('stripe', data)
File "/home/jvo/odoo_versions/odoo_v15/addons/payment/models/payment_transaction.py", line 617, in _handle_feedback_data
  tx._execute_callback()
File "/home/jvo/odoo_versions/odoo_v15/addons/payment/models/payment_transaction.py", line 800, in _execute_callback
  success = getattr(record, method)(tx)  # Execute the callback
File "/home/jvo/odoo_versions/enterprise_v15/sale_subscription/models/sale_subscription.py", line 874, in _reconcile_and_assign_token
  self._reconcile_and_send_mail(tx)
File "/home/jvo/odoo_versions/enterprise_v15/sale_subscription/models/sale_subscription.py", line 906, in _reconcile_and_send_mail
  self.send_success_mail(tx, invoice)
File "/home/jvo/odoo_versions/enterprise_v15/sale_subscription/models/sale_subscription.py", line 1170, in send_success_mail
  return template.with_context(email_context).send_mail(invoice.id)
File "/home/jvo/odoo_versions/odoo_v15/addons/mail/models/mail_template.py", line 269, in send_mail
  values = self.generate_email(res_id, ['subject', 'body_html', 'email_from', 'email_to', 'partner_to', 'email_cc', 'reply_to', 'scheduled_date'])
File "/home/jvo/odoo_versions/odoo_v15/addons/account_edi/models/mail_template.py", line 21, in generate_email
  res = super().generate_email(res_ids, fields)
File "/home/jvo/odoo_versions/odoo_v15/addons/mail/models/mail_template.py", line 221, in generate_email
  result, format = report._render_qweb_pdf([res_id])
File "/home/jvo/odoo_versions/odoo_v15/addons/account/models/ir_actions_report.py", line 47, in _render_qweb_pdf
  return super()._render_qweb_pdf(res_ids=res_ids, data=data)
File "/home/jvo/odoo_versions/odoo_v15/odoo/addons/base/models/ir_actions_report.py", line 819, in _render_qweb_pdf
  html = self_sudo.with_context(context)._render_qweb_html(res_ids, data=data)[0]
File "/home/jvo/odoo_versions/odoo_v15/odoo/addons/base/models/ir_actions_report.py", line 863, in _render_qweb_html
  return self._render_template(self.report_name, data), 'html'
File "/home/jvo/odoo_versions/odoo_v15/odoo/addons/base/models/ir_actions_report.py", line 600, in _render_template
  return view_obj._render_template(template, values).encode()
File "/home/jvo/odoo_versions/odoo_v15/odoo/addons/base/models/ir_ui_view.py", line 1975, in _render_template
  return self.browse(self.get_view_id(template))._render(values, engine)
File "/home/jvo/odoo_versions/odoo_v15/addons/web_editor/models/ir_ui_view.py", line 29, in _render
  return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
File "/home/jvo/odoo_versions/odoo_v15/odoo/addons/base/models/ir_ui_view.py", line 1983, in _render
  return self.env[engine]._render(self.id, qcontext)
File "/home/jvo/odoo_versions/odoo_v15/odoo/tools/profiler.py", line 289, in _tracked_method_render
  return method_render(self, template, values, **options)
File "/home/jvo/odoo_versions/odoo_v15/odoo/addons/base/models/ir_qweb.py", line 74, in _render
  result = super()._render(template, values=values, **compile_options)
File "/home/jvo/odoo_versions/odoo_v15/odoo/addons/base/models/qweb.py", line 134, in _render
  result = .join(rendering)''
File "/home/jvo/odoo_versions/odoo_v15/odoo/addons/base/models/qweb.py", line 221, in render_template
  raise e
File "/home/jvo/odoo_versions/odoo_v15/odoo/addons/base/models/qweb.py", line 219, in render_template
  yield from compiled_fn(self, values, log)
...
File "/home/jvo/odoo_versions/odoo_v15/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.access', <function IrModelAccess.check at 0x7fa9f3bf8d30>, 4, False, 'account.move', 'read', True, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/jvo/odoo_versions/odoo_v15/odoo/addons/base/models/qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
File "<template_674>", line 1050, in template_674
File "<template_674>", line 335, in t_call_content
File "/home/jvo/odoo_versions/odoo_v15/odoo/fields.py", line 3389, in __get__
    return super().__get__(records, owner)
File "/home/jvo/odoo_versions/odoo_v15/odoo/fields.py", line 2603, in __get__
    return super().__get__(records, owner)
File "/home/jvo/odoo_versions/odoo_v15/odoo/fields.py", line 1085, in __get__
    record._fetch_field(self)
File "/home/jvo/odoo_versions/odoo_v15/odoo/models.py", line 3276, in _fetch_field
    self._read(fnames)
File "/home/jvo/odoo_versions/odoo_v15/odoo/models.py", line 3290, in _read
    self.check_access_rights('read')
File "/home/jvo/odoo_versions/odoo_v15/odoo/models.py", line 3538, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
File "<decorator-gen-33>", line 2, in check
File "/home/jvo/odoo_versions/odoo_v15/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
File "/home/jvo/odoo_versions/odoo_v15/odoo/addons/base/models/ir_model.py", line 1812, in check
    raise AccessError(msg)
odoo.exceptions.AccessError: You are not allowed to access 'Journal Entry' (account.move) records.

...

Error when render the template
AccessError: You are not allowed to access 'Journal Entry' (account.move) records.

This operation is allowed for the following groups:
        - Invoicing/Billing
        - Invoicing/Billing Administrator
        - Sales/Administrator
        - Sales/User: Own Documents Only
        - Technical/Show Accounting Features - Readonly
        - User types/Portal

Contact your administrator to request access if necessary.
Template: account.report_invoice_document
Path: /t/t/div/t
Node: <t t-set="display_discount" t-value="any(l.discount for l in o.invoice_line_ids)"/> - - -

opw-2705525, opw-2750550

closes odoo/enterprise#24256

X-original-commit: d9c672a8a391a61b65cdbd3aab8cb3d9b4bb088f
Signed-off-by: Martin Trigaux (mat) <mat@odoo.com>
Signed-off-by: jorenvo <jov@odoo.com>