[FIX] base_automation_hr_contract: fix triggers on date
Automated actions allows to trigger an action based on date, e.g. "2 days after
sale order creation". To make it more useful, Odoo allows to count work days only.
And we could even use work days of specific user, e.g. Salesperson of the sale order.

It turns out, such use case didn't work last 5 years since renamings in `resource` module [1].

STEPS:

1. Make an Automated Action with the following configuration:
* Trigger Condition: Based on Timed Condition
* Delay after trigger date: 1 Days
* Set values for `trg_date_resource_field_id` (Use employee work schedule) and `trg_date_calendar_id` (Use Calendar)
2. Be sure that there are sale orders that have employee with active contract
3. Run Scheduled action *Base Action Rule: check and execute*

BEFORE the patch you see the following error:

> "'resource.calendar' object has no attribute 'schedule_days_get_date'"

Fix it by using correct method name.

Also, this patch deletes a check for `action.trg_date_calendar_id`, which looks
as copy-paste from original `_check_delay` method, while it's not used in the
inherited implementation.

Note. This patch doesn't restore original behavior completly, because support
for `resource_id` parameter (i.e. filtering days by employee's leaves) was
dropped 4 years ago [2]. We may restore this feature in master if needed. As
for now, the features seems unused anyway (nobody noticed the error for 5 years).

[1]: https://github.com/odoo/odoo/commit/be01aaa99ff3ad32b757dd0a61a437dac19fc2c9
[2]: https://github.com/odoo/odoo/commit/975c6c8639b3e62d8f63022e94f7ddb006bd9e2f

opw-2856817

closes odoo/enterprise#39129

X-original-commit: 08c23ae5ce82d5b693a5778ca8b0bd853624f49f
Signed-off-by: Nicolas Lempereur (nle) <nle@odoo.com>
Signed-off-by: Ivan Elizaryev (iel) <iel@odoo.com>
Co-authored-by: nle-odoo <nle@odoo.com>