[FIX] account_reports: unnoticed AttributeError
AttributeError: module 'datetime' has no attribute 'strptime'
Introduced by https://github.com/odoo/enterprise/commit/50dbedbfc634dd3e861033cdf8f9939abee3e3c9

This wasn't spotted by runbot since
1) pylint test on runbot doesn't check no-member errors since it would
raise everywhere because of Odoo architecture
2) the exception is raised inside a try except block, no error is
raised.

closes odoo/enterprise#15178

X-original-commit: d355454068aab4814a12219ed3ae0320131856e6
Signed-off-by: Victor Feyens (vfe) <vfe@odoo.com>