[FIX] account_accountant: missing partner in bank statement move
With an MX company setup
Create an invoice
Send for validation
Create a new bank statement for the invoice without partner
Match the statement with the invoice
Send the payment for validation

Error: Traceback will appear
This is caused by the missing partner_id in bank statement move

opw-3291289

closes odoo/enterprise#43701

Signed-off-by: Laurent Smet (las) <las@odoo.com>