[FIX] website_calendar: use Owner's tz or UTC as a fallback
STEPS:
* create calendar event, add Azure Interior as participant
* open mail.mail with the invitation
* open accept link in incognito window

BEFORE:

  File "/opt/odoo/custom/src/enterprise/website_calendar/controllers/main.py", line 175, in calendar_appointment_view
    tz_session = pytz.timezone(timezone)
  File "/usr/local/lib/python3.5/site-packages/pytz/__init__.py", line 163, in timezone
    if zone.upper() == 'UTC':
AttributeError: 'bool' object has no attribute 'upper'

AFTER:

Owner's tz is used

---

opw-2415703

closes odoo/enterprise#15402

X-original-commit: cf3497e42f5b086f3002d0782c6bbd0a44ba7171
Signed-off-by: Ivan Yelizariev // IEL <yelizariev@users.noreply.github.com>