[FIX] sale_ebay: access 'message_post' method from res.partner
Currently, the error occurs when executing the scheduled action
'EBay: update categories' with apply the wrong credentials for eBay.

Step to produce:

- Install the 'sale_ebay' module.
- Navigate to 'Sale' > 'Configuration' > 'Settings'.
- In the 'eBay' section, intentionally input incorrect values in the following
fields:
        'Developer Key'
        'Sandbox Token'
        'Sandbox App Key'
        'Sandbox Cert Key'
- Manually trigger the scheduled action 'eBay: update categories'.

Error:  ValueError: 'res.users' object has no attribute 'message_post'
while evaluating 'model._cron_sync(True)'

When executing the scheduled action 'EBay: update categories', There's an issue
where the system attempts to access the 'message_post' method from 'res.users'
object [1] and the 'res.users' object has no attribute 'message_post'.

Line[1]: https://github.com/odoo/enterprise/blob/6c8c7dd78f354ba7dc2b2d176243046e1fed26bf/sale_ebay/models/sale_ebay.py#L52-L53

This commit solves this issue by accessing the 'message_post' method from the
'res.partner' object instead of 'res.users'.

sentry-4457508544

closes odoo/enterprise#47506

X-original-commit: f1ccf2ed14d640db728fe24bfd999a3947509c34
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>