[FIX] account_reports: options serialization with journal groups
Create a test account journal group
Go to Accounting -> Reporting -> Trial Balance
Ensure the journal group is selected
Click on the PDF export button

Error will raise
TypeError: Object of type set is not JSON serializable”

This occurs because in the process of gathering options initializer the
system add a `set` to the options, which is not json serializable

opw-3564632

closes odoo/enterprise#50072

X-original-commit: 08d58d80a0baf88af82bbd58b06d8181a0eaf963
Signed-off-by: de Wouters de Bouchout Jean-Benoît (jbw) <jbw@odoo.com>
Signed-off-by: Andrea Grazioso (agr) <agr@odoo.com>