[FIX] sale_renting: update report template to prevent crash
Before this commit, the sale_renting report was failing because of the following tag:

```
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
KeyError: 'pickup_date'
Template: sale_renting.report_rental_order_document
Path: /t/t/div/table/tbody/t/tr/td[2]/span
Node: <span t-field="line.pickup_date"/>
```

closes odoo/enterprise#26469

X-original-commit: f52046b137b2deb41b660958eb2ce8685cc012dd
Signed-off-by: Xavier Dollé (xdo) <xdo@odoo.com>