[FIX] helpdesk: fix helpdesk stage change with custom Many2many field - Go to Helpdesk - Open a ticket - Activate Studio to edit the ticket form - Add a Many2many field related to "helpdesk.ticket" - Go to a ticket form and add another ticket in the newly added Many2many field - Save the ticket - Change the stage from the ticket form The following traceback is generated: ------------------------------------------------------------------------------------------ File "/home/odoo/src/enterprise/helpdesk/models/helpdesk_ticket.py", line 390, in name_get
result.append((ticket.id, "%s (#%d)" % (ticket.name, ticket.id)))

TypeError: %d format: a number is required, not NewId
------------------------------------------------------------------------------------------

opw-2244205

closes odoo/enterprise#10447

X-original-commit: 5203bc4b28b7d51715a5cdcf1c48aa8c92c653f5
Signed-off-by: Nicolas Martinelli (nim) <nim@odoo.com>