[FIX] l10n_in_hr_payroll: run cron job without external id
When user deleted 'Probation' record in employment types and when cron job
run this traceback raises.

To reproduce this issue:
1) Install 'l10n_in_hr_payroll'
2) Update the company as 'IN Company'
3) Open Employees and create an employee record
4) In Employees go to configuration/Employment types and delete probation record
5) Now try to run 'HR Contract: update state' manually in 'scheduled actions'.

Error: A traceback appears : "<class 'ValueError'>: External ID not found in the
system: l10n_in_hr_payroll.l10n_in_contract_type_probation"

On 'update_state' method in 'hr_contract' contract_type_id is referenced from
'l10n_in_hr_payroll.l10n_in_contract_type_probation'.
https://github.com/odoo/enterprise/blob/8985fb7291499caa355b51d232631bb9e6411bb2/l10n_in_hr_payroll/models/hr_contract.py#L27-L33
Therefore in the above use case when triggering the above cron job,
because of that external id is deleted, it will lead to above traceback.

Sentry-4247454345

closes odoo/enterprise#42801

X-original-commit: 8e549a0480abf9f57b14e2e7bef17c2b1e16b8b6
Signed-off-by: Kevin Baptiste <kba@odoo.com>