[FIX] hr_payroll: PY error `'bool' object is not subscriptable`
To reproduce (V16):
 1. Install payroll
 2. Go to Payroll > Contracts > Contracts
 3. Create 2 contracts, with no employee set on it,
    make sure they are both in a different state
    (one new and one running for example)
 4. Go to payroll dashboard
=> JS error, which hide a Python traceback:
```
  ...
  File "/home/odoo/Odoo/code/version/16.0/enterprise/hr_payroll/models/hr_payslip.py", line 1116, in <listcomp>
    group['employee_id'][0] for group in employee_contract_groups if group['state'] == 2]
TypeError: 'bool' object is not subscriptable

```

Issue reason:
 As the contract does not have any employee associated to it,
 it fails to retrieve its value.

After this commit:
 Contract without employee associated are excluded from
 the search domain.
 So contracts searched does always have an employee set on it

OPW-3069633

closes odoo/enterprise#34100

X-original-commit: 5d3ad1c752cff8ef705e56971c2abe666c59644c
Signed-off-by: Yannick Tivisse (yti) <yti@odoo.com>
Signed-off-by: Sens Loan (lse) <lse@odoo.com>