[FIX] hr_referral: fix crash when opening referral jobs and LT exists with no medium
Since odoo/enterprise@9d0c352804 we protect against the removal of utm
campaign and source but not against removal of medium (which are
explicitly permitted)

In such case, when computing hr.job clicks we may ends up crashing with:

```
Traceback (most recent call last):
  ...
  File "/home/odoo/src/enterprise/saas-16.2/hr_referral/models/hr_job.py", line 37, in _compute_clicks
    mapped_data[elem['campaign_id'][0]][elem['medium_id'][0]] = elem['count']
TypeError: 'bool' object is not subscriptable
```

To reproduce:

- Open Referral app, click on "Jobs" and create a "Direct" share link
- Open that link
- Now remove the "Direct" medium
- Open Referral app, click on "Jobs" => it crash with the above
  traceback.

This commit ensure we only fetch link.tracker with a `medium_id` set

closes odoo/enterprise#40254

X-original-commit: d31a4041d8a5b13ff7d9ae07c4871b7e291daeb9
Signed-off-by: Kevin Baptiste <kba@odoo.com>