[FIX] test_l10n_be_hr_payroll_account: remove auto-install
Test module shouldn't be auto-install.

This was discovered truing to mograte templates containing
l10n modules. since l10n_be is installed,
test_l10n_be_hr_payroll_account was installed too.

In 16, the wizard l10n_be_dimona_wizard_action combined with
record "notice_period_wizard" causes a failure in test_mock_crawl
during the pre upgrade tests.

.test_mock_crawl: Mocking menu Payroll > Reporting > Belgium > DIMONA

    2022-12-28 10:22:55,715 17 ERROR 22259264-16-0-all odoo.sql_db: bad query: UPDATE "hr_payslip_employee_depature_notice" SET "first_contract" = NULL, "write_date" = '2022-12-28 10:22:41.090745', "write_uid" = 2 WHERE id IN (1)
    ERROR: null value in column "first_contract" of relation "hr_payslip_employee_depature_notice" violates not-null constraint
    DETAIL:  Failing row contains (1, 48, 1, 1, 2, Doesn't reach his target anymore, superior, without, 2020-04-15, 2020-04-15, null, f, 2022-12-28 10:19:52.572341, 2022-12-28 10:22:41.090745).

This is maybe because of _compute_oldest_contract_id?

Anyway, having a test_module auto install doesn't make sence.

closes odoo/enterprise#35330

X-original-commit: fef9b8eab0a9f95ad7bacccf135633bacc95aa9c
Signed-off-by: Xavier Dollé (xdo) <xdo@odoo.com>