[FIX] mrp: fix planning by workcenter
Since https://github.com/odoo/odoo/commit/926c4d4769db1846d94e2ab5a3e9b02308b0b160
the gantt view retrieves unavailabilities only for workcenter rows leading
to erroneous accumulations when grouping, for example, by stage or by
production.
We are now retrieving unavailabities so that the accumulations are correct.

We notice also, but only in Firefox, that moving the mouse over total pills
sometimes gives
TypeError: ev.target.closest is not a function
  find        (/web_gantt/static/src/gantt_renderer.js:1867)
  onMouseMove (/web_gantt/static/src/gantt_renderer.js:1869)
This because the event's target may be
  - #text "01:28"           (TextPrototype)
rather than
  - <span class="o_gantt... (HTMLSpanElementPrototype)
or
  - <div class="o_gantt...  (HTMLDivElementPrototype)

closes odoo/enterprise#42017

Task: 3305266
X-original-commit: cc59493de2f8401be3442d8bfdb1607ee15e1519
Related: odoo/odoo#123898
Signed-off-by: Steve Van Essche <svs@odoo.com>
Signed-off-by: Jean-Francois Aubert (ajf) <ajf@odoo.com>