[FIX] l10n_ec_edi: create withhold when invoice_date is not set
When the user tries to create withhold while invoice_date is not set traceback
will appear

Steps to produce:
1. install the Ecuadorian Accounting EDI module and switch to its respective
company
2. invoice > new > action > create withholds
Note: Invoice must be in draft state.
Error: AttributeError: 'bool' object has no attribute 'month'

see: https://github.com/odoo/enterprise/blob/adfe654f14fe1cf962e7a8151df6bb47162391be/l10n_ec_edi/wizard/l10n_ec_wizard_account_withhold.py#L300
in the above use case at the time of creating withhold when the invoice_date
field is not set, then the invoice_date field gets a false, which led to the
attribute error.

(2) When user tries to create withhold while the customer field is not set and
the invoice_date field is set, traceback will appear.

Steps to produce:
1. install the Ecuadorian Accounting EDI module and switch to its respective
company
2. invoice > new > add invoice_date > action > create withholds
Note: Invoice must be in draft state
Error -> ValueError: not enough values to unpack (expected 1, got 0)

This fix checks, that the invoice must be posted before creating a withhold.

sentry-4211436445

closes odoo/enterprise#45791

X-original-commit: 511924b73eeda0940158ad20de99e83e4278b5dc
Signed-off-by: Brice Bartoletti (bib) <bib@odoo.com>