[FIX] sale_subscription: changing partner of confirmed subscription failed
Before this commit, when the change partner wizard was used on confirmed
recurring orders, the following error occured:

```
  File "/home/odoo/src/odoo/saas-16.1/addons/sale/models/sale_order.py", line 782, in action_confirm
    raise UserError(_(
odoo.exceptions.UserError: It is not allowed to confirm an order in the following states: cancel, sale, done
```

This commit makes sure to confirm SO in draft and sent state.

closes odoo/enterprise#37483

X-original-commit: d973824bf997ece35bd50081af601c6aa69e9818
Signed-off-by: Kevin Baptiste <kba@odoo.com>