[FIX] social_{facebook,linkedin,twitter}: don't read file directly
Reading an image directly from the filestore is prone to errors when the
image file is deleted.
Moreover it causes issues during upgrades when the filestore is not
available.

Example traceback when the file is missing from the filestore
```
 Traceback (most recent call last):
   File "/tmp/tmpmh88kwtq/migrations/base/tests/test_mock_crawl.py", line 181, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpmh88kwtq/migrations/base/tests/test_mock_crawl.py", line 292, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmpmh88kwtq/migrations/base/tests/test_mock_crawl.py", line 318, in mock_view_form
    [data] = record.read(fields_list)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3016, in read
    return self._read_format(fnames=fields, load=load)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3036, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5662, in __getitem__
    return self._fields[key].__get__(self, type(self))
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1019, in __get__
    self.compute_value(recs)
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/14.0/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4057, in _compute_field_value
    getattr(self, field.compute)()
   File "/home/odoo/src/enterprise/14.0/social_facebook/models/social_post.py", line 41, in _compute_facebook_preview
    else base64.b64encode(open(image._full_path(image.store_fname), 'rb').read()) for image in post.image_ids
   File "/home/odoo/src/enterprise/14.0/social_facebook/models/social_post.py", line 41, in <listcomp>
    else base64.b64encode(open(image._full_path(image.store_fname), 'rb').read()) for image in post.image_ids
 FileNotFoundError: [Errno 2] No such file or directory: '/home/odoo/.local/share/Odoo/filestore/db_23108/f5/f541d3636c124ccdc6fbcc42354bd280f04104f8'
```

Related: odoo/odoo#61037
Specifically: the issue with `bin_size` when reading images.

Observed during upgrade 23108.

closes odoo/enterprise#20522

X-original-commit: 9253648dc3040eebbbc4e9da757f9d8b643b2a4e
Signed-off-by: Christophe Simonis <chs@odoo.com>