[FIX] sale_subscription: fix subscription tax computation
This was causing mirgrations to fail.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/service/server.py", line 1199, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 474, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/14.0/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmp64dwvjff/migrations/sale_subscription/saas~13.2.1.1/end-migrate.py", line 15, in migrate
    util.recompute_fields(cr, "sale.subscription.line", ["price_subtotal"])
  File "/tmp/tmp64dwvjff/migrations/util/orm.py", line 113, in recompute_fields
    records.recompute()
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5891, in recompute
    process(field)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5875, in process
    field.recompute(recs)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1153, in recompute
    self.compute_value(recs)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4057, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoo/src/enterprise/14.0/sale_subscription/models/sale_subscription.py", line 1102, in _compute_amount
    amounts = taxes.compute_all(price, line.currency_id, line.quantity, product=line.product_id, partner=self.analytic_account_id.partner_id)
  File "/home/odoo/src/odoo/14.0/addons/account/models/account_tax.py", line 570, in compute_all
    'name': partner and tax.with_context(lang=partner.lang).name or tax.name,
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 963, in __get__
    record.ensure_one()
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4987, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.partner(1742, 1443, 1514, 1618, 1881, 1447, 1652, 1641, 1565, 1426, 1473, 1508, 1869, 1606, 1528, 1689, 1579, 1683, 1630, 1595, 1692, 1559, 1491, 1430, 1779, 1914, 1867, 1989, 2085, 1793, 1526, 1522, 1520, 2166, 1563, 1749, 1622, 1697, 1624, 2135, 1983, 1495, 1837, 2148, 1920, 1891, 2153, 2216, 2273, 1901, 2103, 1811, 1875, 2071, 2162, 2014, 1916, 2141, 2042, 2004, 1839, 2075, 2021, 1938, 2079, 1924, 1936, 1957, 1969, 1877, 2067, 1887, 2027, 2206, 2069, 2151, 2272, 1918, 2221, 2410, 1930, 2062, 2318, 2316, 2292, 2324, 2394, 2392, 2039, 2429)
```

upg-22387
upg-22389
upg-22397

closes odoo/enterprise#20281

X-original-commit: cec5bed48f499acfb76db10694beee2bc79ba516
Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>