[FIX] documents: Extract AttachmentViewer patch to it's own class
Steps to reproduce
==================

- Go to documents
- Select a few documents
- Open the preview
- Go back to the home menu
- Go to a project task
- Upload an attachment
- Click on the preview
- Press Escape

```
TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at getSelectedDocumentsElements
```

Cause of the issue
==================

The Attachment Viewer patch is applied everywhere, so also outside
documents.

Solution
========

Extract The AttachmentViewer with document specific behaviours into it's
own class

opw-3456439

closes odoo/enterprise#46270

X-original-commit: b8056c51cc8223761ecd9997c367c07b49b32a5f
Related: odoo/odoo#133126
Signed-off-by: Alexandre Kühn (aku) <aku@odoo.com>
Signed-off-by: Hubert Van De Walle <huvw@odoo.com>