[FIX] account_bank_statement_import_csv: import entry as statement
From the Accounting Dashboard, click on a journal (i.e. Miscellaneous
Operations), then 'Favorites>Import records' and load a csv containing a
journal entry

Error: 'amount' is not in list

This occurs since 45c67defa3cb853f73dfbc25d70cb285f1825dfe
When user open the journal entries view, 'default_journal_id' is set in context
and the data import process will try to parse bank statement data

opw-3054896

closes odoo/enterprise#34283

X-original-commit: 2d6f58f583dbdef38be52ff306ea39c34d9e86cb
Signed-off-by: Nicolas Lempereur (nle) <nle@odoo.com>
Signed-off-by: Grazioso Andrea (agr) <agr@odoo.com>