[FIX] web_studio: undo operation crash with previous xpath not matching
Steps to reproduce
==================

- Go to the project task form view
- Open studio
- Drag a new Integer field at the last position of the last column
  (After the Planned Date field).
- Click on "Undo"

```
TypeError: Cannot read properties of null (reading 'arch')
  at get nodeType [as nodeType]
  at get propertiesComponent [as propertiesComponent]
  ...
```

Cause of the issue
==================

The old `activeNodeXpath` is used and since we cancelled the last
operation, it doesn't match anything anymore.

opw-3478585

closes odoo/enterprise#49318

X-original-commit: e5493bda3b1f9f21c780d874991ec6bbe38369d5
Signed-off-by: Lucas Perais (lpe) <lpe@odoo.com>
Signed-off-by: Hubert Van De Walle <huvw@odoo.com>