[FIX] hr_appraisal_survey: remove unused element
Before we got -> AttributeError: 'survey.user_input' object has no attribute 'signature'

task - 2659826

closes odoo/enterprise#22025

Signed-off-by: Kevin Baptiste <kba@odoo.com>