[FIX] account_accountant: missing partner in bank statement move
With an MX company setup
Create an invoice
Send for validation
Create a new bank statement for the invoice without partner
Match the statement with the invoice
Send the payment for validation

Error: Traceback will appear
This is caused by the missing partner_id in bank statement move

opw-3291289

closes odoo/enterprise#45494

X-original-commit: 3a7eac62324fd02c0a18f60d41e609f7d04d69b0
Signed-off-by: Laurent Smet (las) <las@odoo.com>
Signed-off-by: Andrea Grazioso (agr) <agr@odoo.com>