[FIX] sign: fix error on sending without fields
Sending without any added fields now works and does not cause a traceback.
Before this commit, it caused an "AttributeError: 'res.partner' object has no attribute 'mail_sent_order'".
This was due to the typo attempting to get the 'mail_sent_order' value on a 'res.partner' record (self.signer_id) instead of 'sign.send.request.signer' (self.signer_ids).

task-2969322

closes odoo/enterprise#30952

Signed-off-by: Arnaud Joset <arj@odoo.com>