[FIX] account_bank_statement_import: prevent uploading empty files
AttributeError 'bool' object has no attribute 'decode'. This issue occurs because
the user imports the empty files which have no raw data.

steps to reproduce :
1. Install the `Belgium - Import Bank CODA Statements` module
2. Open the accounting module.
3. In the Bank section click on the import statement.
4. Select the empty content file (Any other than the CSV file).
 Traceback generated.

In this commit, we will prevent uploading the empty files to the server.

sentry - 4067071325

closes odoo/enterprise#40366

Signed-off-by: Brice Bartoletti (bib) <bib@odoo.com>