[FIX] sale_account_taxcloud: set a taxcloud_date attribute
Create an SO with a Taxcloud fiscal position. Click "Update Taxes":

  File ".../enterprise/account_taxcloud/models/taxcloud_request.py", line 127, in get_all_taxes_values
    self.taxcloud_date, # useDate
AttributeError: 'TaxCloudRequest' object has no attribute 'taxcloud_date'

Since we do not know yet what the invoice date will be, we will always
use the current date.

Introduced by 664d16a154e3d783f8112c9bf30feea22e01be76.

opw-2410836

closes odoo/enterprise#15088

X-original-commit: e7b21b40c1853e1dd3ed863bc204b02831a90674
Signed-off-by: Nicolas Martinelli (nim) <nim@odoo.com>