[FIX] account_disallowed_expenses:
Traceback was raised here totals[id][1] += values['balance'] * values['account_rate'] / 100

with

TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

because account_rate was None instead of 0

opw:2442217

closes odoo/enterprise#15814

X-original-commit: 10af110fbfd2920d8ae24a254125f2cebb3fd06d
Signed-off-by: William André (wan) <wan@odoo.com>
Signed-off-by: Simon Goffin (sig) <sig@openerp.com>