[FIX] web_studio: handle `res.users` fake field in `_postprocess_access_rights`
Install Studio, open Settings -> Users -> any user, click on the Studio
button

```
  File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 2477, in get_views
    result['views'] = {
  File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 2478, in <dictcomp>
    v_type: self.get_view(
  File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 2665, in get_view
    node = self.env['ir.ui.view']._postprocess_access_rights(node)
  File "/home/odoo/src/enterprise/16.0/web_studio/models/ir_ui_view.py", line 101, in _postprocess_access_rights
    field = self.env[model]._fields[node.get('name')]
KeyError: 'in_group_12'
```

This issue happens because the model `res.users` implements fake field,
which doesn't really exist in the model.
For those fields, we can assume they have no group on the Python definition
of the field.

closes odoo/enterprise#34983

X-original-commit: aab5ddbe124c283cfec4ef69dbd199dd3ebde75c
Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>