[FIX] helpdesk: add missing dependency web_cohort
web_cohort needs to be an explicit dependency of helpdesk
https://github.com/odoo/enterprise/blob/98f42c2bf97794a42e3f87b7b02f152e80c5b18f/helpdesk/views/helpdesk_views.xml#L296

Otherwise we may get
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4205, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4134, in _load_records_create
    return self.create(values)
  File "<decorator-gen-43>", line 2, in create
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_ui_view.py", line 482, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-65>", line 2, in create
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3862, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3934, in _create
    col_val = field.convert_to_column(val, self, stored)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 2402, in convert_to_column
    value = self.convert_to_cache(value, record)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 2414, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for ir.ui.view.type: 'cohort'
```

Steps to reproduce traceback:
1. Setup clean DB version 14.0
2. Uninstall web_cohort
3. Install helpdesk

Observed during the upgrade request upg-12038

closes odoo/enterprise#19653

X-original-commit: e6232014e6d34a0eda0cc53782419228e805980a
Signed-off-by: Nicolas Lempereur (nle) <nle@odoo.com>
Signed-off-by: Alvaro Fuentes <aj-fuentes@users.noreply.github.com>