[FIX] documents_spreadsheet: handle error while no spreadsheet data available
If there is no 'spreadsheet_data' available then traceback will appear.

To reproduce the issue:

1) Install the 'Document' Module
2) Go to the 'Document' App
3) On the left side go to 'Spreadsheet' and create a new spreadsheet if not any.
4) Open any spreadsheet
5) Form the URL change 'spreadsheet_id' any number 1,2,3,4,5 ... etc.

Traceback will appear.

Error: 'bool' object has no attribute 'encode'

In the '_get_spreadsheet_snapshot' function if  'spreadsheet_data' and
'spreadsheet_snapshot' is False  then traceback will raise:
https://github.com/odoo/enterprise/blob/saas-16.2/spreadsheet_edition/models/spreadsheet_collaborative_mixin.py#L169

Therefore, in the above use case, raising Validation Error will resolve
this issue.

sentry-4245514442

closes odoo/enterprise#44497

X-original-commit: d1010e838575853311d711075645a61773ae3eec
Signed-off-by: Lucas Lefèvre (lul) <lul@odoo.com>
Signed-off-by: Urvi Soni (uso) <uso@odoo.com>