[FIX] mrp_workorder_hr{,_account}: include employee cost in SVL
The employee cost is currently not included in the valuation process

To reproduce the issue:
1. Create an employee E:
   - Hourly Cost: 100
2. Edit P_finished's category:
   - Costing Method: FIFO
3. Create two storable products P_compo, P_finished
4. Create a work center WC:
   - Cost per hour per workcenter: 10
   - Requires Log In: True
   - Allowed Employees: E
5. Create a BoM:
   - Product: P_finished
   - Components: 1 x P_compo
   - Operations:
     - add a new operation OP that uses WC
6. Create and confirm a MO with 1 x P_finished
7. Open the tablet view of OP:
8. Log in as E and set the done qty
   - (Wait few seconds)
9. Mark it as done and close the MO
10. Open MO > Cost Analysis
    - Keep the total cost in mind
11. Open MO > Valuation

Error: The value is not the same, the employee cost is not included

When computing the price unit of the finished move, nothing in the
code includes the costs of the employees

OPW-3116944

closes odoo/enterprise#35533

X-original-commit: 47f2a66013fcf6c3f32d30a18270da68058d4db6
Related: odoo/odoo#109340
Related: odoo/upgrade#4220
Signed-off-by: William Henrotin (whe) <whe@odoo.com>