[FIX] delivery_ups: no more _default_warehouse_id
`_default_warehouse_id` for sale orders was replaced by a compute in the
following commit:
 - https://github.com/odoo/odoo/commit/f9f68adb2cdfdfd16bc24c82acae015ddfb9b83a

The closest thing to this field seems to be the warehouse associated to
the user.

```
Traceback (most recent call last):
  File "/home/odoo/src/enterprise/delivery_ups/tests/test_delivery_ups.py", line 205, in test_04_backorder_and_track_number
    warehouse = self.env['sale.order']._default_warehouse_id()
AttributeError: 'sale.order' object has no attribute '_default_warehouse_id'
```

X-original-commit: deb87f9a2ea7e3f1d9f14ac6ac12e29f12006c07
Part-of: odoo/enterprise#34186