[FIX] account_asset_ndt: Fix expected singleton on res_currency
while computing `non_deductible_tax_val` from `AccountAsset`.

In function `_compute_non_deductible_tax_value`, to retrieve the value of
`company_id`, `self` is used instead of the loop object `record`.

This creates a problem when `self` holds more than one record with different
currencies, as `res_currency.round` will fail on `self.ensure_one()`.

This error was spotted during a failed upgrade while installing the module:
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 5196, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/service/server.py", line 1258, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 474, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 199, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 444, in init_models
    env['base'].flush()
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 5641, in flush
    self.recompute()
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 6114, in recompute
    process(field)
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 6098, in process
    field.recompute(recs)
  File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1243, in recompute
    self.compute_value(recs)
  File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1265, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/15.0/addons/mail/models/mail_thread.py", line 411, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4255, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoo/src/enterprise/15.0/account_asset_ndt/models/account_asset.py", line 23, in _compute_non_deductible_tax_value
    record.non_deductible_tax_val = self.currency_id.round(non_deductible_tax_value / quantity)
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/res_currency.py", line 194, in round
    self.ensure_one()
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 5199, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.currency(6, 95, 92, 3)
```

closes odoo/enterprise#26965

X-original-commit: b89a12c9c38c57e57442e2f7fbe4759acf448669
Signed-off-by: William André (wan) <wan@odoo.com>