[FIX] sale_subscription: traceback on group by state
Before this PR, sale_susbcription would crash if the groupby subscription_state
was called on so with no subscription_state.

```
 File "/data/build/enterprise/sale_subscription/models/sale_order.py", line 854, in read_group
    res = sorted(res, key=lambda r: r['subscription_state'])
TypeError: '<' not supported between instances of 'bool' and 'str'
```

taskid : 3244835

closes odoo/enterprise#39110

X-original-commit: 2adf094460b0206c29c7b3c7391cdd7a652045f2
Signed-off-by: Arnaud Joset <arj@odoo.com>
Signed-off-by: Damhaut Florian (flda) <flda@odoo.com>