[FIX] {snailmail_}account_followup: filter partners with missing info
If a user does not have `snailmail_account_followup` and uses server action
`action_manually_process_automatic_followups` to process followup
reports then the user will face error.

steps to produce:
- Install `Accounting`.
- Uninstall `snailmail_account_followup`.
- Accounting > Customers > Follow-up Reports > select a follow up report with
  status `in_need_of_action` and run the server action
 `Process Automatic Follow-ups`.

Error: `AttributeError:
'account_followup.followup.line' object has no attribute 'send_letter'
`

Our commit moves the snailmail address validity check to an override in
the snailmail_account_followup module.

sentry-4522827500

closes odoo/enterprise#50707

X-original-commit: b4df90e74d4aba55e2caa0f5fce455dda6a3cc90
Signed-off-by: Habib Ayob (ayh) <ayh@odoo.com>