[FIX] account_reports: Avoid parameter error when CoA is not set
Avoid error on tests:
```
 Traceback (most recent call last):
    File "/root/enterprise/account_followup/tests/test_followup.py",
    line 263, in setUpClass
         super(TestAccountFollowupReports, cls).setUpClass()
            File "/root/enterprise/account_reports/tests/common.py",
            line 46, in setUpClass
                 cls.skipTest("l10n_generic_coa not installed")
                  TypeError: skipTest() missing 1 required positional
                  argument: 'reason'
```

closes odoo/enterprise#9614

X-original-commit: d6d4632514187fe2cd954f432537ee9128089e44
Signed-off-by: Nicolas Martinelli (nim) <nim@odoo.com>