[FIX] mrp_workorder_hr_account: missing dependency
The model located https://github.com/odoo/enterprise/blob/16.0/mrp_workorder_hr_account/report/mrp_cost_structure.py inherits from
`report.mrp_account_enterprise.mrp_cost_structure`, hence it's dependency should contain `mrp_account_enterprise` which is missing.

Impacted versions:
- error occurs in v16, I think this is the only version when this problem occurs.

Current behaviour:
During the upgrade error happens:
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/service/server.py", line 1289, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-14>", line 2, in new
  File "/home/odoo/src/odoo/16.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/16.0/odoo/modules/registry.py", line 91, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 482, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 371, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 196, in load_module_graph
    model_names = registry.load(cr, package)
  File "/home/odoo/src/odoo/16.0/odoo/modules/registry.py", line 241, in load
    model = cls._build_model(self, cr)
  File "/home/odoo/src/odoo/16.0/odoo/models.py", line 643, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
TypeError: Model 'report.mrp_account_enterprise.mrp_cost_structure' does not exist in registry.

```

closes odoo/enterprise#36749

X-original-commit: 1f496e265ac7af1948791e14abdd36b80322181b
Signed-off-by: William Henrotin (whe) <whe@odoo.com>