[FIX] approvals: allow deletion of draft approval
There is a business check on attachment unlink that needs to access
approval state. This is why the attachment needs to be unlinked before
the approval itself.

steps to reproduce:
- create a draft approval and attach a document
- delete the approval.

before this commit:
odoo.exceptions.MissingError: Record does not exist or has been deleted.
(Record: approval.request(8,), User: 2)

after this commit:
approval is deleted

opw-3558437

closes odoo/enterprise#51105

X-original-commit: 9f03cb8d1080f762ebb02133fc202f397c4fb736
Signed-off-by: Yannick Tivisse (yti) <yti@odoo.com>
Signed-off-by: Nicolas Danhier (nda) <nda@odoo.com>