[FIX] l10n_de_pos_cert: check for orders before parsing json
Steps to reproduce:

1. install and configure l10n_de_pos_cert and create a point of sale
2. open the session
3. make a cash in or cash out operation
4. attempt to close the session

Traceback:
```
File "<2771>", line 527, in template_2771
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
IndexError: tuple index out of range
Template: l10n_de_pos_cert.dsfinvk_cash_point_closing_template
Path: /t/t/t[4]
Node: <t t-esc="orders[0].id"/>
```
This happens because in lines
https://github.com/odoo/enterprise/blob/12690625b4c248a1c833ec44e123da25d1eff3f6/l10n_de_pos_cert/models/pos_session.py#L56-L57
it checks for `self.order_ids` even though `orders` might be empty,
like in the current scenario. As a result orders need to be checked
too.

opw-3423586

closes odoo/enterprise#45501

X-original-commit: c255b50eccab8169532e2c7b8708dfae99c6231b
Signed-off-by: Joseph Caburnay (jcb) <jcb@odoo.com>
Signed-off-by: Ahmad Khanalizadeh (khah) <khah@odoo.com>