[FIX] hr_work_entry_contract_planning: publish planning
Steps :
Go to planning > next week > publish > publish.

Issue :
ValueError: cannot compare False with datetime.

Cause:
In PlanningSlot._create_work_entries(),
we make a query to get slots, to which we left join HRWorkEntries,
and we aggregate those values in work_entry_ids.
If one doesn't have any, the resulting row will contain [None].
Then we call browse those work_entry_ids and write on them.
So we get hr.work.entry(None,...).write(vals).
This causes issue in later treatments.

Fix :
Filter the actual ids.

closes odoo/enterprise#32739

X-original-commit: 9470df91ab7346c9128cebbd0e68c395fc4171ae
Signed-off-by: Laurent Stukkens (ltu) <ltu@odoo.com>