[FIX] asset: access state correctly
Before this commit, There was trackback on deleting asset which is in `'open', 'paused', 'close'` state due to wrongly accessing state field.

```
raise UserError(_('You cannot delete a document that is in %s state.') % self._fields['state']._description_selection(self.env)).get(asset.state)
AttributeError: 'UserError' object has no attribute 'get'
```

Now we are correctly accessing state field.

Follow up on ef1286f6f96c998db5697806e691193b5eb1c9cf

closes odoo/enterprise#12823

X-original-commit: ba68796c61dc618b9c383a168ed1160653f49c26
Signed-off-by: Simon Goffin (sig) <sig@openerp.com>