Cherry pick of 2abbaa405ddc09b98df16da33801206050e876eb failed
stdout:

stderr:

closes odoo/enterprise#9978

Error: could not apply 2abbaa405d... [FIX] web_studio: display all widgets in sidebar
Hint: after resolving the conflicts, mark the corrected paths
Hint: with 'git add <paths>' or 'git rm <paths>'
Hint: and commit the result with 'git commit'
Signed-off-by: Aaron Bohy (aab) <aab@odoo.com>