[FIX] sign: allow to render PDF with crash
Before this commit, the PDF rendering would crash with the following traceback due to a change of API.
It would only appear when account_edi was installed.

```
  File "/home/dbo/src/enterprise/sign/models/sign_request.py", line 834, in _edit_and_sign
    self._sign(signature)
  File "/home/dbo/src/enterprise/sign/models/sign_request.py", line 863, in _sign
    sign_request._sign()
  File "/home/dbo/src/enterprise/sign/models/sign_request.py", line 365, in _sign
    self._send_completed_document()
  File "/home/dbo/src/enterprise/sign/models/sign_request.py", line 395, in _send_completed_document
    self._generate_completed_document()
  File "/home/dbo/src/enterprise/sign/models/sign_request.py", line 588, in _generate_completed_document
    pdf_content, __ = report_action.with_user(public_user).sudo()._render_qweb_pdf(self.id)
  File "/home/dbo/src/odoo/addons/account/models/ir_actions_report.py", line 42, in _render_qweb_pdf
    return super()._render_qweb_pdf(res_ids=res_ids, data=data)
  File "/home/dbo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 775, in _render_qweb_pdf
    collected_streams = self._render_qweb_pdf_prepare_streams(data, res_ids=res_ids)
  File "/home/dbo/src/odoo/addons/account_edi/models/ir_actions_report.py", line 18, in _render_qweb_pdf_prepare_streams
    and len(res_ids) == 1 \
TypeError: object of type 'int' has no len()
```

Note: since https://github.com/odoo-dev/odoo/commit/8bdd8cffd02bf34302582cf8a4c6b15583f10729 this commit is not formally needed
anymore but we decive to keep it to presever consistancy and robustness regarding future changes.

closes odoo/enterprise#27154

Taskid: 2849324
Signed-off-by: William Braeckman (wbr) <wbr@odoo.com>