[FIX] hr_contract_salary: search single record on onchange_advantage
When the user creates an advantage in salary package configurator
keeping 'Salary Structure Type' and 'Advantage Field' same as another
advantage. Now try to access salary configurator and make change on
an advantage, the error will occur.

To reproduce the issue:
- Install Salary Configurator module.
- Go to Employees module > Configuration > Advantages.
- If there is an existing advantage create its duplicate or create two
advantages keeping 'Salary Structure Type' and 'Advantage Field' same.
- Now Go to Recruitment module > All Applications > Open one application >
Generate Offer > Click on 'Configure your package' button in chatter.
- Now in Salary Configurator make changes in one of the same advantage.

Error: ValueError: Expected singleton: hr.contract.salary.advantage(1, 2)

The issue is occuring because we are getting two records in advantage
over here -
https://github.com/odoo/enterprise/blob/790a6a7c6ff6e561e643553c1a8e2b15a4dfeb3e/hr_contract_salary/controllers/main.py#L734-L736

To solve this issue limit is set to one while performing search operation.

sentry-4451619732

closes odoo/enterprise#47221

Signed-off-by: Sofie Gvaladze (sgv) <sgv@odoo.com>