[FIX] l10_pe_edi : Traceback when printing invoice
Issue: When trying to print an invoice with one line that doesn't
contain a product, there is a traceback saying
```
File "/home/odoo/src/enterprise/14.0/l10n_pe_edi/models/account_move.
py", line 169, in _l10n_pe_edi_get_spot
max_percent = max(self.invoice_line_ids.mapped('product_id.l10n_pe_withh
old_percentage'))
ValueError: max() arg is an empty sequence
```

Steps to reproduce :

1- Create an invoice
2- Create an invoice line with a note only (no product)
3- Save
4- Try to print invoice

Side-Note: since we check right after if `not max_percent`, the
developer of this code probably expected that there might be no
maximum, except that it needs to be explicitly written as default in
Python

opw-2658816 parent-task: 2641982

closes odoo/enterprise#21490

X-original-commit: 7a0a66cdd8d917b8c12af9bd76fdb116402c0928
Signed-off-by: Laurent Smet <smetl@users.noreply.github.com>