[FIX] sale_subscription{,_taxcloud}: missing renaming type -> move_type
Following https://github.com/odoo/odoo/commit/d675dbaa4c7174591e0e7c1a3caf3e76877312ce

Also updated tests to be more consistant

Regex used to fin problematic lines:
`\b(default_)?type\b.*\b(out|in)_(invoice|refund)\b`

Fix traceback
```
Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Wrong value for ir.attachment.type: 'out_invoice'
```

closes odoo/enterprise#15917

X-original-commit: 856a15a3aef391f48ed01e5893859e927777cc50
Related: odoo/odoo#64951
Signed-off-by: Quentin De Paoli (qdp) <qdp@openerp.com>
Signed-off-by: William André (wan) <wan@odoo.com>