[FIX] hr_payroll: prevent typeerror when 'date_to' is removed
TypeError: combine() argument 1 must be datetime.date, not None

This issue occurs when user attempting to remove the default value of 'date_to'
while creating employee payslips, and subsequently clicking outside the form
before saving the record.

After applying this commit will fix this issue.

sentry-4228660216

closes odoo/enterprise#42373

X-original-commit: afc1c3b5d5ae345b8ab89ac9a8a77d770c34f530
Signed-off-by: Yannick Tivisse (yti) <yti@odoo.com>