[FIX] social_push_notifications: prevent an error if multiple web visitors
Currently, the error occurs when sending a push notification from a 'Visitor',
who have multiple 'website visitors'.

Steps to reproduce:

- Install a `social_push_notifications` and 'web_studio' modules.
- Go to Settings> General Settings, And Enable website push notifications in
'Email & Marketing' section.
- Open another browser or an incognito window, Visit your website as a visitor,
and allow notifications.
- Go back to the main browser and open Website>Reporting>Visitors, Open
 'Administrator' record
- Tick the boolean field 'Push Notifications Enabled' to enable push
notifications.
 - Add the 'Push Subscriptions' field using 'web_studio'
This field is for testing purposes and will show how many website visitors are
available.
- If there are multiple web visitor then Click on the
'Send Push Notification' button to open the 'Post' form view.
- Set a message and post it.

Error:  Expected singleton: website.visitor.push.subscription(6, 8) while
evaluating 'model._cron_publish_scheduled()'

When sending a push notification from a particular visitor whose website has
multiple 'website visitors', There's an issue where the system attempts to
access the 'push_token' from the multiple records of 'push_subscription_ids'[1].

Line[1]: https://github.com/odoo/enterprise/blob/2784921e93853d09f5052b6054389e78c2af42fc/social_push_notifications/models/social_account.py#L70

This commit solves this issue by removing 'push_token' in the filter function as
'push_token' is a required field, so there's no need for an additional iteration
to check 'push_token' separately.

sentry-4486410114

closes odoo/enterprise#49549

X-original-commit: 904ef042c5dc85c5d0d00db4b121c684023e78b9
Signed-off-by: Warnon Aurélien (awa) <awa@odoo.com>