[FIX] sale_stock_renting : set same from and to on S/N renting without error
Steps :
Install Rental and Inventory.
Inventory > Settings > Traceability > Enable Lots & S/N.
Rental > Create a Product:
	> Invetory > Tracking : By Unique S/N
Create a Rental Order and add this Product to the Order Lines.
In the wizard that pops up, set the same dates for "from" and "to"
dates and click on Apply.

Issue :
TypeError: can only concatenate list (not "sale.order.line") to list.

Cause :
Clicking on Apply calls _get_unavailable_qty_and_lots(),
which calls _get_active_rental_lines().
When "from" and "to" are equal, _get_active_rental_lines()
returns 2 empty lists and some SOLs.
Later, we try to concatenate those results together.

Fix :
Instead of returning empty lists, return empty records.

opw-2793666

closes odoo/enterprise#25466

X-original-commit: 9235d5cf35abe4a847c9bb8e3761398c3a7b76ee
Signed-off-by: Victor Feyens (vfe) <vfe@odoo.com>