[FIX] web_studio: race condition with systray item
This commit fixes a race condition in the studio systray item.
Before this commit, there was a small time window, after a new
action is inserted into the dom by the action service, during which
the studio icon might have been clickable, even though the new
action wasn't editable. If the user clicked on the icon at that
particular moment, there was a crash.

Even though it's not very likely in practice (but still possible),
it was a cause of non deterministic runbot failure in tours, e.g.

FAIL: TestUi.test_new_app_and_report
Traceback (most recent call last):
  File "/data/build/enterprise/web_studio/tests/test_ui.py", line 15, in test_new_app_and_report
    self.start_tour("/web?debug=tests", "web_studio_new_report_basic_layout_tour", login="admin")
  File "/data/build/odoo/odoo/tests/common.py", line 1616, in start_tour
    return self.browser_js(url_path=url_path, code=code, ready=ready, **kwargs)
  File "/data/build/odoo/odoo/tests/common.py", line 1596, in browser_js
    self.fail('%s\n%s' % (message, error))
AssertionError: The test code "odoo.startTour('web_studio_new_report_basic_layout_tour')" failed
Uncaught (in promise)Error
    at _openStudio (http://127.0.0.1:8069/web/assets/439-cffdd9e/web.assets_backend.min.js:10957:38)
    at Object.open (http://127.0.0.1:8069/web/assets/439-cffdd9e/web.assets_backend.min.js:10965:8)
    at StudioSystray._onClick (http://127.0.0.1:8069/web/assets/439-cffdd9e/web.assets_backend.min.js:10940:24)
    at Object.extra.handlers.click__331__ (eval at _compile (http://127.0.0.1:8069/web/assets/438-e8d595e/web.assets_common.min.js:1016:178), <anonymous>:12:185)
    at invokeHandler (http://127.0.0.1:8069/web/assets/438-e8d595e/web.assets_common.min.js:838:144)
    at handleEvent (http://127.0.0.1:8069/web/assets/438-e8d595e/web.assets_common.min.js:842:92)
    at HTMLDivElement.handler (http://127.0.0.1:8069/web/assets/438-e8d595e/web.assets_common.min.js:844:58)
    at trigger_mouse_event (http://127.0.0.1:8069/web/assets/438-e8d595e/web.assets_common.min.js:5180:200)
    at Class._click (http://127.0.0.1:8069/web/assets/438-e8d595e/web.assets_common.min.js:5178:392)
    at Class.auto (http://127.0.0.1:8069/web/assets/438-e8d595e/web.assets_common.min.js:5177:1238)
	at NotEditableActionError (http://127.0.0.1:8069/web/assets/439-cffdd9e/web.assets_backend.min.js:10943:470)
	at _openStudio (http://127.0.0.1:8069/web/assets/439-cffdd9e/web.assets_backend.min.js:10956:37)
	at open (http://127.0.0.1:8069/web/assets/439-cffdd9e/web.assets_backend.min.js:10964:7)
	at _onClick (http://127.0.0.1:8069/web/assets/439-cffdd9e/web.assets_backend.min.js:10939:23)
	at extra.handlers.click__331__ (:11:184)
	at invokeHandler (http://127.0.0.1:8069/web/assets/438-e8d595e/web.assets_common.min.js:837:143)
	at handleEvent (http://127.0.0.1:8069/web/assets/438-e8d595e/web.assets_common.min.js:841:91)
	at handler (http://127.0.0.1:8069/web/assets/438-e8d595e/web.assets_common.min.js:843:57)
	at trigger_mouse_event (http://127.0.0.1:8069/web/assets/438-e8d595e/web.assets_common.min.js:5179:199)
	at _click (http://127.0.0.1:8069/web/assets/438-e8d595e/web.assets_common.min.js:5177:391)
	at auto (http://127.0.0.1:8069/web/assets/438-e8d595e/web.assets_common.min.js:5176:1237)
	at exec (http://127.0.0.1:8069/web/assets/438-e8d595e/web.assets_common.min.js:5256:496)
	at _to_next_running_step (http://127.0.0.1:8069/web/assets/438-e8d595e/web.assets_common.min.js:5255:820)

Part-of: odoo/enterprise#24869