[FIX] iot: PoS stuck with negative payment on ingenico
Before this fix:
Making a transaction with a negative payment amount on
an ingenico payment terminal would cause the PoS to hang
forever in a "request sent" state with no way to cancel it.
The request on the IoT would crash with a traceback
```
IngenicoDriver.py: Traceback (most recent call last):
  File "/home/pi/odoo/addons/hw_drivers/iot_handlers/drivers/IngenicoDriver.py", line 791, in action
    self._outgoingMessage( "TransactionRequest", transactionId=data['TransactionID'], amount=data['amount'])
  File "/home/pi/odoo/addons/hw_drivers/iot_handlers/drivers/IngenicoDriver.py", line 781, in _outgoingMessage
    self._protocolId, messageType, self._getSequence(), **kwargs)
  File "/home/pi/odoo/addons/hw_drivers/iot_handlers/drivers/IngenicoDriver.py", line 450, in __init__
    body, mdc = self._generateBody(self.messageTypeId)
  File "/home/pi/odoo/addons/hw_drivers/iot_handlers/drivers/IngenicoDriver.py", line 508, in _generateBody
    int(str(self.amount), 16).to_bytes(4, byteorder='big'))) +\
OverflowError: can't convert negative int to unsigned
```
but nothing is sent back to the server, so it keeps waiting for a reply

After this commit:
Any error is caught and sent back to the PoS.
For the specific case of the negative payment, a better error
message have been added to be more precise regarding the issue

opw-3193179

closes odoo/enterprise#41147

X-original-commit: 12660cfcb96fa2c0adfe28a1269f83ba66714a1c
Signed-off-by: Sens Loan (lse) <lse@odoo.com>