[FIX] {sale_purchase,account}_inter_company_rules: company's child
The sync SO-PO or INV-BILL does not work with company's child

To reproduce the issue:
1. Have two companies C1, C2
2. On C1 side, Settings:
   - Inter-Company Transactions: Synchronize Sales and Purchase Order
3. Switch to C2
4. Create a partner P:
   - Individual
   - Company name: C1
5. Create and confirm a SO:
   - Customer: P
6. Switch to C1
7. Open purchase orders

Error: There is not any PO for the confirmed SO

Same issue will occur with invoices/bills.

OPW-3319118

closes odoo/enterprise#44860

X-original-commit: 4bec0ef5c6d9320a999e7e4027ca3aa9a4de4d41
Signed-off-by: Arnold Moyaux (arm) <arm@odoo.com>
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>