[FIX] sale_renting: fully qualified report view
Potentially, users can add new fields using custom modules,
hence new columns.

It's therefore a good practice to fully qualify the columns
when defining a report view.

The case where the issue occurs is a 12.0 database
updating to 13.0 which has a column `product_id`
defined in another implied table than `sale_order_line`

```
2021-04-15 11:04:12,218 457 INFO db_8460 odoo.modules.registry: module sale_renting: creating or updating database tables
2021-04-15 11:04:12,329 457 ERROR db_8460 odoo.sql_db: bad query: CREATE or REPLACE VIEW sale_rental_report as (
        select
            sol.id,
            order_id,
            product_id,
            product_uom_qty  / (u.factor * u2.factor) as quantity,
            qty_delivered  / (u.factor * u2.factor) as qty_delivered,
            qty_returned  / (u.factor * u2.factor) as qty_returned,
            product_uom,
            order_partner_id as partner_id,
            salesman_id as user_id,
            categ_id,
            product_tmpl_id,
            generate_series(pickup_date::date, return_date::date, '1 day'::interval)::date date,
            price_subtotal / (date_part('day',return_date - pickup_date) + 1) as price,
            sol.company_id,
            sol.state,
            sol.currency_id
        from sale_order_line sol
            join product_product p on p.id=sol.product_id
            join product_template pt on p.product_tmpl_id=pt.id
            join uom_uom u on u.id=sol.product_uom
            join uom_uom u2 on u2.id=pt.uom_id
        where is_rental
        )
ERROR: column reference "product_id" is ambiguous
LINE 5:             product_id,
```

upg-15188

closes odoo/enterprise#18511

X-original-commit: 76320f9aabac2f373d0a3367a1b7cf7fa5aa5d4a
Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>