[FIX] industry_fsm_sale: fix usage of unavailable field "is_fsm"
Step to reproduce:
1. Install module "sale_project"
2. In Project > Configuration > Settings, turn on "Recurring Tasks"
3. Create a recurrent task
4. Set the "next_recurrence_date" for the recurrence ahead of today
5. Run scheduled action " Project: Create Recurring Tasks"
=> error: 'project.task' object has no attribute 'is_fsm'

Reason:
"is_fsm" is used in "sale_project" module, but is defined in the "industry_fsm" module
and "sale_project" module does not depend on that module.

opw-2412370

closes odoo/enterprise#15288

X-original-commit: b9efbf42cf1e03e0663f5b099e2a6070424d2693
Related: odoo/odoo#63325
Signed-off-by: Nicolas Martinelli (nim) <nim@odoo.com>