[FIX]planning: Traceback when sending an open shift
Steps to reproduce:
create an open shift > click on 'send & publish'

Observed behavior:
AssertionError: Invalid value res.company(1,) in domain term ('company_id', '=', res.company(1,))

Expected behavior:
- No traceback
- The open shift is correctly sent to employees with
--> either 1) this role set by default 2) no roles set by default
--> or to all employees if no role is set on the shift

Task ID 2312381
Enterprise PR #12222

Signed-off-by: Yannick Tivisse (yti) <yti@odoo.com>