[FIX] l10n_mx_reports: Invalid field 'tag_ids' when loading financial report
Following the validation of the report line domains with
odoo/enterprise#18228

`l10n_mx_reports/data/account_financial_report_data.xml` no longer
loads correctly because the domain is invalid for account.move.line.

```
  File "/home/odoo/src/enterprise/12.0/account_reports/models/account_financial_report.py", line 455, in _validate_domain
    raise ValidationError(error_format % (record.name, str(e)))
odoo.tools.convert.ParseError: "Error while validating the domain of line 101 Caja:
Invalid field 'tag_ids' in leaf "<osv.ExtendedLeaf: ('tag_ids', 'in', [5]) on account_move_line (ctx: )>"
None" while parsing /home/odoo/src/enterprise/12.0/l10n_mx_reports/data/account_financial_report_data.xml:55, near
<record id="mx_afrl_101" model="account.financial.html.report.line">
            <field name="name">101 Caja</field>
            <field name="code">MX_COA_101</field>
            <field name="sequence" eval="0"/>
            <field name="level" eval="2"/>
            <field name="figure_type">no_unit</field>
            <field name="parent_id" ref="mx_afrl_1"/>
            <field name="domain" eval="[('tag_ids', 'in', [ref('l10n_mx.account_tag_101_01'),])]"/>
        </record>
```

The reason for this lies in the fact l10n_mx_reports uses financial report lines in an uproper way to only store the domains for account.account records to use in a custom report: https://github.com/odoo/enterprise/blob/12.0/l10n_mx_reports/models/coa.py#L59. We fix this by overriding the constraint in order to adapt the check made for those lines.

upg-10593

closes odoo/enterprise#18541

X-original-commit: e61aabf42e78376b4ea396911d211a83a2f89ea2
Signed-off-by: oco-odoo <oco-odoo@users.noreply.github.com>