[FIX] project_enterprise: plan existing task without timezone
This traceback appears when user removes timezone from preferences and when user
tries to plan existing task in Gantt view.

Steps to reproduce:
1) Create a "new DB" and Click on "Settings" > "Users & Companies" > "Users".
2) Click on "Mitchell Admin" and in form view, open "Preferences" page.
3) Set the "Timezone" field as empty.
4) Install "project_enterprise" module.
5) Open "Project" > click on "My Tasks" > open "Gantt" view.
6) Now, in Mitchell Admin column, hover to any task and then click on
   magnifying glass(plan existing).
7) Now click on any task having value of project other than private.

Error: AttributeError: 'bool' object has no attribute 'upper'

When user removes the "tz" from preferences, the value of "tz_info"
becomes "False".

See:
https://github.com/odoo/enterprise/blob/cb520b0bf404d5829b2daab2519958213215bbf4/project_enterprise/models/project_task.py#L348-L350

So, when it tries to use "upper" method from "timezone" for value "False"

See:
https://github.com/odoo/enterprise/blob/cb520b0bf404d5829b2daab2519958213215bbf4/project_enterprise/models/project_task.py#L360

thus this error is being generated.

sentry-4344775086

closes odoo/enterprise#48050

X-original-commit: 87abbb959e3e675e0281b9f41dc2325df93730e0
Signed-off-by: Xavier Bol (xbo) <xbo@odoo.com>