[FIX] hr_payroll: employee payslip when date_to field removed
When user create new employee payslip, select employee and remove date of
'date_to' field, a traceback will appear.

Steps to reproduce the issue:
- Go to Payroll > Payslips > All Payslips
- Create New Employee Payslip
- Select any Employee
- Remove date of 'date_to' field.

Error: A traceback appears:
'ValueError: Compute method failed to assign hr.payslip
(<NewId 0x7f3063ad3eb0>,).is_wrong_duration'

https://github.com/odoo/enterprise/blob/cd42b0de992cc2acc8a403c828c06cf9501a3c6c/hr_payroll/models/hr_payslip.py#L840
Here, when user remove date of date_to field in employee slip,
It will not get any value for date_to field, when it will return period_name.
So it will lead to above traceback.

sentry-4306109394

closes odoo/enterprise#44001

X-original-commit: 230852c8369e84d93a6611e525b2c700a887658d
Signed-off-by: Sofie Gvaladze (sgv) <sgv@odoo.com>
Signed-off-by: Kevin Baptiste <kba@odoo.com>