[FIX] pos_preparation_display: prevent passing of object in search domain
ProgrammingError: can't adapt type 'pos.category' is generated when we follow
below steps this is because the in search domain category_ids is required
numbers(ids) but in function 'preparation_displays' was passed object.

Steps to reproduce:
1) Install 'point_of_sale' module > Activate 'Preparation Display' from
   Configuration > Settings
2) Open pos session having preparation display like 'Bar'.
3) Create and validate a order > Close the session.
4) Click on 'Orders' > 'Preparation Display' and select 'Open Display' according
    to order.
5) Click on order item and the error will be generated in backend.

By applying this, `categories.ids` will be passed instead of `category`.

sentry - 4063535802

closes odoo/enterprise#39666

X-original-commit: b0951540597a9f7395e5b28473c0f45487f17d6b
Signed-off-by: Joseph Caburnay (jcb) <jcb@odoo.com>