[FIX] timesheet_grid: fix my_team_timesheet not found
Problem
-------

Since the inheritance order is not garantuee between
hr_timesheet.hr_timesheet_line_my_timesheet_search and timesheet_grid.timesheet_view_search
the view timesheet_grid.hr_timesheet_line_inherit_my_timesheet_search
that depends on the first one but hide a filter defined in the second
one. In some case (ie: migrated database), this can lead to the
following error:

ValueError: Element '<filter name="my_team_timesheet">' cannot be located in parent view

Solution
--------
To make sure timesheet_grid.timesheet_view_search is loaded before
hr_timesheet.hr_timesheet_line_my_timesheet_search. Make the latter
inherit from the view define in timesheet_grid

closes odoo/enterprise#15266

X-original-commit: ac1bb366c99b4a3b4118313d6bda341b4ffb567d
Signed-off-by: Yannick Tivisse (yti) <yti@odoo.com>