[FIX] sale_amazon: prevent canceling orders with confirmed pickings
This commit fixes blocked syncing in case of canceling an order at Amazon that
already has confimed picking in Odoo.

Because amazon doesn't provide sandbox, I tested this update with a test I made
based on customer case. So, run the test:

    --db-filter=.*  -i sale_amazon --test-tags /sale_amazon:TestAmazon.test_sync_pickings_undo

it emulates following
STEPS:
* create order on Amazon
* sync to Odoo
* process picking
* cancel order on Amazon
* sync to Odoo

BEFORE:

```
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/tools/misc.py", line 849, in deco
    return func(*args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/tools/misc.py", line 849, in deco
    return func(*args, **kwargs)
  File "/opt/odoo/auto/addons/sale_amazon/tests/test_amazon.py", line 501, in test_sync_pickings_undo
    self.account._sync_orders(auto_commit=False)
  File "/opt/odoo/auto/addons/sale_amazon/models/amazon_account.py", line 345, in _sync_orders
    order_data, orders_api)
  File "/opt/odoo/auto/addons/sale_amazon/models/amazon_account.py", line 447, in _process_order
    order.with_context(canceled_by_amazon=True).action_cancel()
  File "/opt/odoo/auto/addons/sale_amazon/models/sale.py", line 37, in action_cancel
    self.write({'amazon_cancellation_pending': True})
  File "/opt/odoo/auto/addons/sale_stock/models/sale_order.py", line 160, in action_cancel
    self.mapped('picking_ids').action_cancel()
  File "/opt/odoo/auto/addons/stock/models/stock_picking.py", line 671, in action_cancel
    self.mapped('move_lines')._action_cancel()
  File "/opt/odoo/auto/addons/stock/models/stock_move.py", line 1302, in _action_cancel
    raise UserError(_('You cannot cancel a stock move that has been set to \'Done\'.'))
odoo.exceptions.UserError: ("You cannot cancel a stock move that has been set to 'Done'.", '')
```

AFTER: warning message is posted to the order

X-original-commit: 570f6312b293633efe319c238a30b7674a534405

Notes for v14 forward port:
* syncing canceled order from odoo to amazon was deleted in v14: https://github.com/odoo/enterprise/commit/58b31312d254750402e87884fdb79a83002ecb1a
* stock.picking.action_done is private in v14: https://github.com/odoo/odoo/commit/0c6488a95aa50aa3102aac9d89da09c18081d088

closes odoo/enterprise#15922

X-original-commit: 2463d1f704d65fa956f2434684ef328e28fba1fb
Signed-off-by: Antoine Vandevenne (anv) <AntoineVDV@users.noreply.github.com>