[FIX] project_forecast: Manage users after archiving project used in planning
What are the steps to reproduce your issue ?

    1. Install "project_forecast"
    2. Create a projectX with taskA
    3. Create new plan with taskA on projectX and "publish & send"
    4. Archive taskA and projectX

What is currently happening ?

    cannot manage Users
       > ValidationError: Your task is not in the selected project

What are you expecting to happen ?

    Manage users without ValidationError

Why is this happening ?

    Because the task is archived, so it will not belong to "project_id.tasks" in the constrain

How to fix the bug ?

    Ignore archived records

opw-2390943

closes odoo/enterprise#14999

X-original-commit: 801d500689556bc08dffbe243cf126982c213da8
Signed-off-by: Nicolas Martinelli (nim) <nim@odoo.com>
Signed-off-by: Achraf <abz-odoo@users.noreply.github.com>