[FIX] mail_mobile: do not crash on approval of message
When approving a message in the moderation queue, the notification
crashes in mail_mobile due to msg_value being False

  msg_type = msg_vals.get('message_type') or msg_sudo.message_type
  AttributeError: 'bool' object has no attribute 'get'

This is because the method _moderate_accept from mail module calls
_notify_thread without any value in msg_value

_notify_record_by_ocn from mail_mobile assumes msg_value is a dict
while False is a possible value

Introduced at 201ad00df4bb868d7ea8e2ea238

closes odoo/enterprise#17041

X-original-commit: 64310590a0f86994ecb29fbef46ae90eb2e3b7e3
Signed-off-by: Martin Trigaux (mat) <mat@odoo.com>