[FIX] web_studio: unable to import studio customizations
Steps to reproduce
==================

- Edit some views with studio
- Save and exit studio
- Go to the home menu
- Open studio
- On the top left, click on Customizations > Export
- Import the downloaded zip

```SQL
bad query:
            INSERT INTO ir_model_data (module,name,model,res_id,noupdate,studio)
            VALUES
('studio_customization','odoo_studio_res_part_f3c7daa6-d3f8-4dca-a7c4-dea2796ebfe0','ir.ui.view',431,false,t)
            ON CONFLICT (module, name)
            DO UPDATE SET (model, res_id, write_date) =
                (EXCLUDED.model, EXCLUDED.res_id, now() at time zone 'UTC')
                WHERE (ir_model_data.res_id != EXCLUDED.res_id OR ir_model_data.model != EXCLUDED.model) AND NOT
ir_model_data.noupdate
            RETURNING module, name, model, res_id, create_date, write_date

ERROR: column "t" does not exist
LINE 3: ...7daa6-d3f8-4dca-a7c4-dea2796ebfe0','ir.ui.view',431,false,t)
```

opw-3514268

closes odoo/enterprise#48070

X-original-commit: 68c83026e205144ad56c7de34c7b0833d56f9b05
Signed-off-by: Hubert Van De Walle <huvw@odoo.com>