[FIX] documents_spreadsheet: fix many2one operator in pivot view
When generating a spreadsheet from a pivot view, the values of m2o
fields are added up instead of being counted.

To reproduce the error:
(Need point_of_sale,documents_spreadsheet)
1. Open a POS session
2. Process 3 orders
3. Close the session
4. Point of Sale > Reporting > Orders - Pivot View
    (Note: the number of orders is 3, which is correct)
5. Insert in Spreadsheet

Error: On spreadsheet, the number of orders is incorrect (the value
corresponds to the sum of the order identifier of each POS order line)

OPW-2551030

closes odoo/enterprise#19910

X-original-commit: 379221a6995525991fa64e8ad2056799cb555bfa
Related: odoo/odoo#74328
Signed-off-by: Nicolas Lempereur (nle) <nle@odoo.com>
Signed-off-by: agr-odoo <agr-odoo@users.noreply.github.com>