[FIX] account_reports: raise UserError if no multicurrency
When a user tries to access 'Unrealized Currency Gains/Losses' accounting
report with single currency activated the error will occur.

Steps to reproduce:
1. Turn on developer mode.
2. Install Accounting module.
3. Keep only one currency active.
4. Go to Accounting > Configuration > Management > Accounting Reports >
'Unrealized Currency Gains/Losses'
5. Create Menu Item of 'Unrealized Currency Gains/Losses'
6. Now open report 'Unrealized Currency Gains/Losses' from Accounting >
Reporting, the error will occur

Error: SyntaxError: syntax error at or near ")"
LINE 2: ...ITH custom_currency_table(currency_id, rate) AS ((VALUES )),

The issue is occurring when currency_rates is missing in options -
https://github.com/odoo/enterprise/blob/cb520b0bf404d5829b2daab2519958213215bbf4/account_reports/models/account_multicurrency_revaluation_report.py#L174

To solve this issue a UserError has been raised when we not get
more than one currency active.

sentry-4372099370

closes odoo/enterprise#47757

X-original-commit: 2e94b1b3bb4e889c8905551bcdc6ab617836aae6
Signed-off-by: John Laterre (jol) <jol@odoo.com>