[FIX] (l10n_be_)hr_contract_salary: fix traceback
Steps:
Install : l10n_lu_hr_payroll and hr_contract_salary

Go to (lu) employee contract - Generate Offer and click on it.

We get:
AttributeError: 'hr.contract.salary.offer' object has no attribute
'contract_type_id'

This is because 'contract_type_id' is defined on 'hr.contract.salary.offer'
in l10n_be_hr_contract_salary

closes odoo/enterprise#44480

X-original-commit: 065db919ac6dd92205ff0b468e93038d13f14f74
Signed-off-by: Kevin Baptiste <kba@odoo.com>
Signed-off-by: Sofie Gvaladze (sgv) <sgv@odoo.com>