[FIX] l10n_nl_intrastat: fix export EXPORT (CBS) in NL localization
Steps to reproduce:
1. Set the company with country Netherlands
2. Install modules "account_accountant" and "l10n_nl_intrastat"
3. Create a customer in another EU country, for example, Germany
4. Create an invoice with the customer and complete other intrastat information
5. Go to Accounting > Reporting > Audit Reports > Intrastat Report
6. Click the button "EXPORT (CBS)"
=> AttributeError: 'account.move' object has no attribute 'number'

Reason:
The invoice was in "account.invoice" model but refactored as "account.move"
model since v13. And the "number" attriubte should be "name" therefore.

opw-2423105

closes odoo/enterprise#15795

X-original-commit: 0a624319810bb093f5f826528c12bf69e178ed1f
Signed-off-by: agr-odoo <agr-odoo@users.noreply.github.com>