[FIX] mrp_account_enterprise: avoid traceback when access cost analysis
Steps to reproduce the bug:
- Configure Product Category All to use FIFO automated valuation
- Create two products that are storable with category All: “P1” and “C1”
- Set costs on the products:
    - “P1”: 40
    - “C1”: 25
- On”P1” create a BoM with Product B as the component
- Create an MO and scrap the component into negative quantities
- Complete the MO and view the Cost Analysis, it works.

- Purchase and receive the component product so that the negative inventory is revalued for the scrap move:
    - in the PO -> C1 = 47

- Try to view the Cost Analysis

Problem:
Traceback is triggered: Error when render the template
ValueError: Expected singleton: stock.valuation.layer(7, 11)
<span t-esc="scrap.stock_valuation_layer_ids.unit_cost"
t-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: currency}"/>

opw-3574431

closes odoo/enterprise#50646

X-original-commit: b13593c8125876a0682a3308a2199208940a1cc2
Signed-off-by: William Henrotin (whe) <whe@odoo.com>
Signed-off-by: Djamel Touati (otd) <otd@odoo.com>