[FIX] delivery_fedex: fix traceback intra-india delivery
Issue

    - Setup a company and a customer with addresses in India
      (used data from task 58746)
    - Create a quote > confirm
    - Delivery note > Fedex international > Validate

    AttributeError: 'NoneType' object has no attribute 'Purpose'

Cause

    The CommercialInvoice object is not generated.

Solution

    As it was generated before, I generate it only if it doesn't exists
    yet.

OPW-2167301

closes odoo/enterprise#7830

X-original-commit: 496d7f5a1977582844a552450dd7d5e84aa997ac
Signed-off-by: Jason Van Malder <jvm-odoo@users.noreply.github.com>