[FIX] hr_payroll: prevent typeerror when 'date_to' is removed
TypeError: combine() argument 1 must be datetime.date, not None

This issue occurs when user attempting to remove the default value of 'date_to'
while creating employee payslips, and subsequently clicking outside the form
before saving the record.

After applying this commit will fix this issue.

sentry-4228660216

closes odoo/enterprise#42659

X-original-commit: 7aa6fbddb4d4b07d1d73c7a3944ff0aca1b6f3d7
Signed-off-by: Yannick Tivisse (yti) <yti@odoo.com>