[FIX] account_asset: Maximum recursion depth while computing asset_remaining_value and asset_depreciated_value
Steps to reproduce the bug:

- Create an automated action AA on model account.move triggered on creation & update
- Create an asset model AM with method "straight line", duration 200 months and a fixed asset account FAA
- Edit FAA and enable allow reconciliation and set automate asset with create in draft
- Create a vendor bill VB with one line set with FAA as account and 5000€ as unit price
- Confirm VB, an asset A  will be automatically generated
- Go to A, set AM as asset model and confirm

Bug:

RecursionError: maximum recursion depth exceeded while calling a Python object

From the traceback, we noticed that:
- the base automation reads the field asset_remaining_value;
- because the field is not in cache, the compute method of this field is invoked;
- it assigns a new field asset_depreciated_value to compute on a record that is not part of 'self';
- as this unexpected assignment is not part of the computation, it triggers an call to write() (the assignments that are part of the computation do not invoke write);
- the call to write() triggers the base automation;
- go back to the first step,

opw:3422406

closes odoo/enterprise#45344

Signed-off-by: Cedric Snauwaert <csn@odoo.com>
Co-authored-by: simongoffin <sig@odoo.com>