[FIX] l10n_ma_hr_payroll: handle traceback while update payroll data
When the schedule action `Payroll: Update data` will run the user will face
a value error. Because it will try to update the data file
'hr_contribution_register_data.xml' which is not present in our
standard code base.

steps to produce:
- Install `l10n_ma_hr_payroll`.
- Settings > Technical> Automation > Schedule Actions > Payroll: Update data.
- Click on Run Manually.

Error: traceback appears: "ValueError: <class 'FileNotFoundError'>: "File not
found: l10n_ma_hr_payroll/data/hr_contribution_register_data.xml" while
evaluating 'model._update_payroll_data()'"

After applying this commit user will not face this error when the scheduled
action will run.

sentry-4327485063

closes odoo/enterprise#44515

X-original-commit: 5dc2b743f7939282b797ffa9f3ed7344c921274a
Signed-off-by: Sofie Gvaladze (sgv) <sgv@odoo.com>
Signed-off-by: Minaxi Vanani (miva) <miva@odoo.com>