[FIX] delivery_*: add mount method to MockedSession
Before this commit, there was an issue with certain builds using a more
recent version of the `zeep` library.

The following traceback occured:
```
odoo.addons.delivery_dhl.tests.test_delivery_dhl:245
ERROR: TestMockedDeliveryDHL.test_01_dhl_basic_be_domestic_flow
Traceback (most recent call last):
  File "/data/build/enterprise/delivery_dhl/tests/test_delivery_dhl.py", line 245, in test_01_dhl_basic_be_domestic_flow
    super().test_01_dhl_basic_be_domestic_flow()
  File "/data/build/enterprise/delivery_dhl/tests/test_delivery_dhl.py", line 73, in test_01_dhl_basic_be_domestic_flow
    choose_delivery_carrier.update_price()
  File "/data/build/odoo/addons/delivery/wizard/choose_delivery_carrier.py", line 76, in update_price
    vals = self._get_shipment_rate()
  File "/data/build/odoo/addons/delivery/wizard/choose_delivery_carrier.py", line 67, in _get_shipment_rate
    vals = self.carrier_id.rate_shipment(self.order_id)
  File "/data/build/odoo/addons/delivery/models/delivery_carrier.py", line 176, in rate_shipment
    res = getattr(self, '%s_rate_shipment' % self.delivery_type)(order)
  File "/data/build/enterprise/delivery_dhl/models/delivery_dhl.py", line 120, in dhl_rate_shipment
    res = self._rate_shipment_vals(order=order)
  File "/data/build/enterprise/delivery_dhl/models/delivery_dhl.py", line 136, in _rate_shipment_vals
    srm = DHLProvider(self.log_xml, request_type="rate", prod_environment=self.prod_environment)
  File "/data/build/enterprise/delivery_dhl/models/dhl_request.py", line 27, in __init__
    self.client = self._set_client('rate.wsdl', 'Rate')
  File "/data/build/enterprise/delivery_dhl/models/dhl_request.py", line 35, in _set_client
    client = Client('file:///%s' % wsdl_path.lstrip('/'))
  File "/usr/lib/python3/dist-packages/zeep/client.py", line 71, in __init__
    transport if transport is not None else self._default_transport()
  File "/usr/lib/python3/dist-packages/zeep/transports.py", line 41, in __init__
    self.session.mount("file://", FileAdapter())
AttributeError: 'MockedSession' object has no attribute 'mount'
```

This commit ensures that the `mount`, as well as the `close` methods are
callable in zeep.transport.requests.Session for the versions using it.

The path for the init of the zeep.Client was changed from a `file://` to
a relative path to avoid calling Session.get from the zeep.Transport, as
well.

X-original-commit: a753123fc78be133522b48d72229b55bf585c5c9
Part-of: odoo/enterprise#34761